### PR TITLE
Add github action to run check on package

### PR DESCRIPTION
**Pull request by ruflin**
To have this pass, also some cleanup to the yaml files was needed.

### CODE REVIEW

**Comment by ruflin** [comment]
@legrego I guess some approval is needed to run the Github actions.

**Comment by legrego** [comment]
@ruflin it's not giving me any option to allow/deny these actions. I might have to merge it first. Thanks for putting this together!

**Review by legrego — APPROVED** [review]

**Comment by legrego** [comment]
It ran after merging:
CleanShot 2023-08-22 at 08 21 03@2x

**Comment by ruflin** [comment]
Glad to see it runs. I'll try to keep improving it further to potentially also to a quick Elasticsearch / Kibana setup and test the install command against it.

**Pull request merged**
